# Generated by Django 5.1.4 on 2025-01-15 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(default='Anonymous', max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SongAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.author')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.song')),
            ],
            options={
                'unique_together': {('song', 'author')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(through='myapp.SongAuthor', to='myapp.author'),
        ),
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.genre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.song')),
            ],
            options={
                'unique_together': {('song', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(through='myapp.SongGenre', to='myapp.genre'),
        ),
    ]
